# Generated by Django 4.2.18 on 2025-03-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, default='events_picture/default.jpg', null=True, upload_to='events_picture/'),
        ),
    ]
