# Generated by Django 4.2.18 on 2025-03-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_event_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default='post_pictures/default.jpg', null=True, upload_to='post_pictures/'),
        ),
    ]
