# Generated by Django 4.2.18 on 2025-03-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0003_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='post_pictures/'),
        ),
    ]
