# Generated by Django 4.2.18 on 2025-03-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0003_post_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
