# Generated by Django 4.2.18 on 2025-03-20 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0004_alter_post_picture'),
        ('social_media', '0004_delete_news'),
    ]

    operations = [
    ]
