# Generated by Django 4.2.18 on 2025-03-20 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0005_merge_0004_alter_post_picture_0004_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, message='Price cannot be negative.'), django.core.validators.MaxValueValidator(50.0)]),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, default='university_logos/default.png', null=True, upload_to='university_logos/'),
        ),
    ]
